### ISSUE TITLE
Plugin applies LLVM .clang-format on refactor -> rename

### ISSUE THREAD

**Issue by ivan-golub** [benoitsan/BBUncrustifyPlugin-Xcode#100]
When refactor-rename is performed, plugin tries to find .clang-format file in wrong folder.
My preferences:
- v 2.1.1
- custom .clang-format flie
- format on save
- perform xcode syntax-aware indenting

Here what Im getting in log.

Marker - Jun 24, 2015, 11:34:15
2015/06/24 11:34:35:941  Formatting using Clang Format at path “/Users/ivangolub/Library/Application Support/Developer/Shared/Xcode/Plug-ins/UncrustifyPlugin.xcplugin/Contents/Resources/clang-format“ with configuration at path “(null)“
2015/06/24 11:34:35:964  Parser Warning: Can't find usable .clang-format, using LLVM style

**Comment by benoitsan** [comment]
Thanks. Fixed.
