### ISSUE TITLE
not working in xcode 6.4(6E35b)

### ISSUE THREAD

**Issue by iVanPan** [benoitsan/BBUncrustifyPlugin-Xcode#102]
Today i update xcode 6.4 from Mac Store,and find that the plugin is not working any more.

**Comment by version4** [comment]
me too

**Comment by dmi3j** [comment]
This worked for me
```
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add `defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID`
```

See details here https://github.com/supermarin/Alcatraz/issues/307#issuecomment-117340589

**Comment by Cross22** [comment]
The Alcatraz fix did not work for me. However, I tried installing BBUncrustify AFTER updating to 6.4.
It is visible in Windows/Plugin Manager, but there is no menu item under Edit.

**Comment by dmi3j** [comment]
@Cross22 Try to run command AFTER plugin install and re-launch Xcode.

**Comment by Cross22** [comment]
That's what I tried. No luck.
