### ISSUE TITLE
Cant use in Xcode Version 6.4 (6E35b)

### ISSUE THREAD

**Issue by nwericyu** [benoitsan/BBUncrustifyPlugin-Xcode#103]
by using curl -SL https://raw.githubusercontent.com/benoitsan/BBUncrustifyPlugin-Xcode/master/install.sh | sh

After restart xcode, the format code menu still not exist.

Os Version: Mac OSX 10.10.3

**Comment by benoitsan** [comment]
The release version is not yet up-to-date for Xcode 6.4 but the master branch is so you need to build the plugin from source.
