### ISSUE TITLE
programatically parse an objective-c file from NSURL

### ISSUE THREAD

**Issue by johndpope** [benoitsan/BBUncrustifyPlugin-Xcode#104]
I did poke around - but I'm seeking clarification on source code implementation

if I have a file nsurl 

how can I programatically parse the objective-c file?

Thanks for insight.

JP

**Comment by benoitsan** [comment]
Hi John,

Not sure to understand your intent. I mean, it's not a formatting library but an Xcode plugin. 

If you want the entry point for the formatters: look at the classes `CFOClangFormatter `and `CFOUncrustifyFormatter `, these classes do the reformatting job using Clang or Uncrustify. The plugin uses them in the method `+ (CFOFormatter *)formatterForString:presentedURL:error:` in `XCFXcodeFormatter` class.

**Comment by johndpope** [comment]
thanks

**Comment by johndpope** [comment]
I'm building an objective-c to swift converter - > check it out http://objc2swift.io
