### ISSUE TITLE
some variables dont work

### ISSUE THREAD

**Issue by pikaboo** [benoitsan/BBUncrustifyPlugin-Xcode#105]
I put 

 Add or remove space after ')' of 'if', 'for', 'switch', and 'while'
sp_after_sparen                           = remove   # ignore/add/remove/force

 Add or remove space between ')' and '{' of 'if', 'for', 'switch', and 'while'
sp_sparen_brace                           = remove   # ignore/add/remove/force

however my code looks like this after the format
        if(_version == nil)
	{
		_version = [[[NSBundle mainBundle] infoDictionary] objectForKey:@"CFBundleVersion"];
	}

**Comment by benoitsan** [comment]
Probably not an issue related to the plugin. Please take a look at Uncrustify and make sure that the formatting error doesn't happen if you run uncrustify in command line on your source file. (https://github.com/bengardner/uncrustify).
