### ISSUE TITLE
Remove verbose log by default "BBUncrustifyPluginVersion loaded"

### ISSUE THREAD

**Issue by OdNairy** [benoitsan/BBUncrustifyPlugin-Xcode#108]
This line produce log each time I run `xcodebuild` or `gym`. 
https://github.com/benoitsan/BBUncrustifyPlugin-Xcode/blob/master/Classes/XCFPlugin.m#L46
This make log produce useless information.

**Comment by benoitsan** [comment]
Thanks for the feedback. It's fixed in 2.1.4 https://github.com/benoitsan/BBUncrustifyPlugin-Xcode/releases/tag/2.1.4
