### ISSUE TITLE
Crashes Xcode 7.1.1 on launch

### ISSUE THREAD

**Issue by JanX2** [benoitsan/BBUncrustifyPlugin-Xcode#110]
Please get back to me, if you can’t reproduce this. :)

**Comment by benoitsan** [comment]
Hi Jan, I can't reproduce the crash. Could you give me more details?

I installed latest version 2.1.4 (https://github.com/benoitsan/BBUncrustifyPlugin-Xcode/releases/tag/2.1.4) in `~/Library/Application Support/Developer/Shared/Xcode/Plug-ins` using Xcode 7.1.1 (7B1005) and the plugin is loaded correctly.
