### ISSUE TITLE
indent comment after comma once and again

### ISSUE THREAD

**Issue by czwuwei** [benoitsan/BBUncrustifyPlugin-Xcode#111]
* XCode7.1.1
* Objective-C
* Uncrustify.cfg 0.61

I had a objc source:
```objc
NSDictionary* json = @{
      @"key1" : @"value1",     // TODO confirm value
      @"key2" : @"value2"
};
```
Everytime I save(auto format) the source, the comment `// TODO confirm value` will be push back.
Could you confirm this?

<img width="812" alt="2015-11-20 19 10 34" src="https://cloud.githubusercontent.com/assets/11752201/11297261/87f2450a-8fba-11e5-99d9-07282667577d.png">

<img width="817" alt="2015-11-20 19 11 06" src="https://cloud.githubusercontent.com/assets/11752201/11297267/8e3f88c8-8fba-11e5-9022-4d15ba23d054.png">

**Comment by benoitsan** [comment]
It's not something related to the plugin. Formatting is done using Clang Formatter or Uncrustify.
