### ISSUE TITLE
Config option to add or remove space around '=' in @property getter or setter override.

### ISSUE THREAD

**Issue by foehammer88** [benoitsan/BBUncrustifyPlugin-Xcode#112]
I've looked all around the config file and I can't seem to find this option. But an option to add or remove space around the '=' operator in a @property getter or setter override would be helpful, because the current add or remove space around '=' ("sp_assign"), seems to add or remove space around @property getter and setter assignment too.

**Comment by benoitsan** [comment]
The goal of the plugin is to format code using Uncrustify rules. This kind of issue is an issue related to Uncrustify itself.

**Comment by foehammer88** [comment]
@benoitsan, if this is an issue with Uncrustify, will it be fixed, if you closed this issue?
