### ISSUE TITLE
Lacks option to explicitly select project language

### ISSUE THREAD

**Issue by parapaul** [benoitsan/BBUncrustifyPlugin-Xcode#114]
We have c++ project and when trying to use "Format Selected Lines" on some lines of an .h file there's an error in log:
>Uncrustify error — exit code 1 (Parsing: SomeHeader.h as language OC ...

It would be great to have an option in BBUncrustifyPlugin Preferences to explicitly set project language (in our case it would be cpp) that will be passed with uncrustify option '-l'.

**Comment by benoitsan** [comment]
Fixed. See https://github.com/benoitsan/BBUncrustifyPlugin-Xcode/pull/131
