### ISSUE TITLE
Plugin not loading in Xcode 7.3

### ISSUE THREAD

**Issue by mvoelkl** [benoitsan/BBUncrustifyPlugin-Xcode#122]
Plugin (correctly placed under ~/Library/Application Support/Developer/Shared/Xcode/Plug-ins) is not being loaded in Xcode 7.3.

Temporary fix: http://stackoverflow.com/questions/19110899/xcode-plugins-stopped-working/30366096#30366096

**Comment by guykogus** [comment]
Should be resolved in PR:
https://github.com/benoitsan/BBUncrustifyPlugin-Xcode/pull/123

**Comment by benoitsan** [comment]
Just pushed version 2.1.6 which contains the fix. Go to https://github.com/benoitsan/BBUncrustifyPlugin-Xcode/releases/tag/2.1.6
