### ISSUE TITLE
Space before/around exclamation operator

### ISSUE THREAD

**Issue by bettimms** [benoitsan/BBUncrustifyPlugin-Xcode#125]
How to remove space before/around exclamation operator?!

**Comment by Phando** [comment]
Any luck with this? I would love to use uncrustify with swift, but it ads spaces around the ! and ? operators.

**Comment by bettimms** [comment]
For ? there's a solution but not for !.

**Comment by benoitsan** [comment]
I'm sorry but it's not an issue related to the plugin, please take a look at the documentation of the parsers themselves.
