### ISSUE TITLE
Use system uncrustify or clang format

### ISSUE THREAD

**Issue by pankkor** [benoitsan/BBUncrustifyPlugin-Xcode#129]
Because uncrustify updates more often than this plugin which is 2 version behind atm (0.61 vs 0.63) it would be nice to have an ability to use a system uncrustify to have a wider control over a version you want to use.

**Comment by benoitsan** [comment]
It's already supported. The plugin will use the system binary, if found, at `/usr/local/bin/uncrustify`. Explained in readme https://github.com/benoitsan/BBUncrustifyPlugin-Xcode#tips

**Comment by pankkor** [comment]
@benoitsan Great! Didn't notice that. Consider it solved then.
