### ISSUE TITLE
C/C++ Header file formatted as Objective-C header

### ISSUE THREAD

**Issue by mgee** [benoitsan/BBUncrustifyPlugin-Xcode#28]
With version 1.0.4 C/C++ header files are formatted with the -l OC flag because they have a .h extension.

Here is the responsible line:
https://github.com/benoitsan/BBUncrustifyPlugin-Xcode/commit/785cde939d1c714d33ebb1d263ad62ad52aaff46#commitcomment-3912998

A solution would be to only include the -l OC flag if a corresponding .m file is also present.

**Comment by MartinMoizard** [comment]
+1 to solve this, this is pretty annoying.
