### ISSUE TITLE
xcode not formatting code

### ISSUE THREAD

**Issue by oliver-dungey** [benoitsan/BBUncrustifyPlugin-Xcode#57]
I know this one has been raised before but I think there still might be an issue here. I'm using xcode 5.1 with BBUncrustifyPlugin-Xcode 2.0.3 and I have found that UncrustifyX will happily find my configuration file in the root of the project directory (or the various home directory options) if it's named .uncrustifyconfig or uncrustify.cfg but my source files are in a sub directory and never get formatted unless I put a configuration file in every directory. This seems to contradict the instructions.

Seems to me that the logic in UncrustifyX for finding config files might be different from the plugin, dunno.

It would be very handy if the preferences page stated which configuration files it had found and which it was going to use on a given project.

FYI If I use Clang instead of uncrustify it all works nicely.

**Comment by niebloomj** [comment]
how were you able to find out what the offending lines were?

**Comment by srosmd** [comment]
I'm having this issue as well. Xcode 6.3, Mac OS X 10.10. I can format the files using my .cfg file in uncrustify, but it doesn't execute the formatting in Xcode. It was working great a few days ago. Maybe the new command line tools from Apple broke this somehow?

**Comment by benoitsan** [comment]
I have added a log viewer. At this time, the log is pretty limited but you will perhaps find an issue in it.

1. Build the plugin from sources. 
2. Reproduce the issue.
3. Go to Edit > Format Code > View Log

![screen shot 2015-04-15 at 23 38 55](https://cloud.githubusercontent.com/assets/528847/7169774/c83d6282-e3c8-11e4-8df3-e232c9eb48f9.png)
