### ISSUE TITLE
.clang-format style isn't applied

### ISSUE THREAD

**Issue by alanf** [benoitsan/BBUncrustifyPlugin-Xcode#81]
Setup:
* I compiled clang-format 3.6 from source symlinked it to `/usr/local/bin/clang-format` (based on reading of where the source searches for this binary)

In Preferences:
* Set formatter to Clang, Clang Style: custom file
* Copy `.clang-format` to repo's top-level directory OR setup a custom _clang-format file and replace contents of file with custom format
* Verify that the file is correctly referenced by going to `Edit Clang Configuration` in the menu

Now, with an ObjC file open, select `Format Active File.`

Result: the file appears to be formatted with default configuration, LLVM style
Expected: the file would be formatted using the custom rules.

**Comment by benoitsan** [comment]
I could not reproduce the issue. I see that you filed the issue 1 month ago, if you still have the issue, please fill an update and I will look into it.
