### ISSUE TITLE
Ancient version of DiffMatchPatch

### ISSUE THREAD

**Issue by JanX2** [benoitsan/BBUncrustifyPlugin-Xcode#85]
I love BBUncrustifyPlugin. Imagine my surprise when I found out that it is using code that I wrote/ported. :)

Just a heads-up that you are using an ancient version of DiffMatchPatch in BBUncrustifyPlugin-Xcode. Get the current one here:
https://github.com/JanX2/google-diff-match-patch-Objective-C

**Comment by benoitsan** [comment]
Thanks Jan for the feedback. It's now up-to-date (https://github.com/benoitsan/BBUncrustifyPlugin-Xcode/commit/93b026719548c5a13e40795659eae9ba434d310b). It's a very useful library ;)

**Comment by JanX2** [comment]
Great! Glad to be of service. :)
