### ISSUE TITLE
Edit Configuration uncrustify does not work

### ISSUE THREAD

**Issue by TofPlay** [benoitsan/BBUncrustifyPlugin-Xcode#92]
Hi,
![xcode 6 2 - edit uncrustify configuration](https://cloud.githubusercontent.com/assets/1082222/6734996/a5520138-ce5b-11e4-9ad0-1d1ac468f7fb.png)
If I open and edit my uncrystify.cfg with UncrustifyX the new configuration does not apply when I save my sources.
Regards
Tof

**Comment by benoitsan** [comment]
If you edit a configuration with UncrustifyX, you need to export it in UncrustifyX to save the changes. It's not an issue related to this plugin. All the plugin does is opening a source file with a given configuration in  UncrustifyX.

**Comment by TofPlay** [comment]
> you need to export it in UncrustifyX to save the changes
That's what I do of course!

**Comment by benoitsan** [comment]
I tested here and it works. It should work and I don't think it's related to plugin. Each time you uncrustify using the plugin the config is read from the configuration file. Make sure that the configuration file is modified after you change a setting in UncrustifyX.
