### ISSUE TITLE
Different config for each Xcode Project

### ISSUE THREAD

**Issue by syky27** [benoitsan/BBUncrustifyPlugin-Xcode#93]
Hi, this is not bug! I have suggestion, would it be possible to chose specific config for project in Xcode, lets say, that I have git repo, where multiple programmers are working on project and the config is in this git repo as well. So it would be awesome if I could chose what config to use for specified project. For example chose by default config in root of project...

If it sound stupid please tell me...

Anyway, great job for making this plugin!

**Comment by syky27** [comment]
Completely irelevant, my bad...

**Comment by benoitsan** [comment]
The plugin will use the first configuration file found in this order:
1. Configuration file found in the current directory of the source file.
2. Each parent directories of the source file.
3. Your Home folder and ~/.uncrustify/uncrustify.cfg

So lets say you have a project with subproject1 (team1) and subproject2 (team2), you can use a structure like that:
```
root project folder
	| subproject1
		| config_file -> team1

	| subproject2
		| config_file -> team2
```
There are some differences between Clang and Uncrustify but the whole logic is explained in the preferences window (see attached screenshot).

![screen shot 2015-04-07 at 19 10 36](https://cloud.githubusercontent.com/assets/528847/7028970/fe6284c0-dd59-11e4-904c-01efb0421419.png)

**Comment by syky27** [comment]
Yeah, I found it after I wrote this issue, feeling really stupid now, sorry...

**Comment by benoitsan** [comment]
No worries.
