### ISSUE TITLE
Use it within run script

### ISSUE THREAD

**Issue by Antondomashnev** [benoitsan/BBUncrustifyPlugin-Xcode#96]
Hi,
First of all thanks for the such a cool plug in.

Can I format my code by ru script when I'm building the app?

**Comment by benoitsan** [comment]
Hi Anton, no the purpose of this project is to be a plugin for Xcode. I suggest you to search on Google for scripting Uncrustify or Clang. There are a lot of threads about that. For example, you can use a git hook as explained here https://github.com/wikimedia/apps-ios-wikipedia

**Comment by Antondomashnev** [comment]
Hi Benoit,

Thanks for the response. I'll take a look on clang scripts.

On Wednesday, 22 April 2015, Benoit Bourdon <notifications@github.com>
wrote:

> Closed #96
> <https://github.com/benoitsan/BBUncrustifyPlugin-Xcode/issues/96>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benoitsan/BBUncrustifyPlugin-Xcode/issues/96#event-287484622>
> .
>


-- 
-------
Anton Domashnev || Conichi, iPhone Developer
mob .: +7 926 683 1069 anton.domashmev@conichi.com
<anton.domashnev@empatika.com>
anton.domashnev@gmail.com <anton.domashnev@empatika.com>
Skype: anton_domashnev
