### ISSUE TITLE
not work in Xcode 6.3.2

### ISSUE THREAD

**Issue by Whirlwind** [benoitsan/BBUncrustifyPlugin-Xcode#97]
the menu item gone in the Xcode 6.3.2

**Comment by benoitsan** [comment]
It works with Xcode 6.3.2.

Make sure to install the latest version 2.1.1 https://github.com/benoitsan/BBUncrustifyPlugin-Xcode/releases/tag/2.1.1

If it doesn't work:

1. Uninstall the plugin.
2. Launch Xcode.
3. Quit Xcode.
4. Install the plugin.
5. Relaunch Xcode.

**Comment by EvgenyKarkan** [comment]
Hi! 
I am using v1.0.5.
After update Xcode to v6.3.2 - plugin is gone from 'Edit' menu item.
I manually added DVTPlugInCompatibilityUUIDs - E969541F-E6F9-4D25-8158-72DC3545A6C6 ( for Xcode 6.3.2) - but still no luck - plugin still missed in 'Edit' menu

Any chances how to fix it?

**Comment by benoitsan** [comment]
No, Apple changed some behaviours with the latest Xcode. As I said, use the latest version https://github.com/benoitsan/BBUncrustifyPlugin-Xcode/releases/tag/2.1.1

**Comment by EvgenyKarkan** [comment]
Ok, thanks. I understand.
In new version can I re-use my custom .cfg file?

**Comment by benoitsan** [comment]
yes, it's explained in the readme and in the preference window.

**Comment by EvgenyKarkan** [comment]
Thanks again! 
PS - great plugin BTW :+1:
