### ISSUE TITLE
Can the Setup File be used the UncrustifyX.app default?

### ISSUE THREAD

**Issue by narlei** [benoitsan/BBUncrustifyPlugin-Xcode#99]
I'm using a default setup for my all projects, then I need use one file configuration for each project.

Can the Setup File be used the UncrustifyX.app default?

Thank's

**Comment by benoitsan** [comment]
Hi Narlei, yes you can manage this. You will find all the needed info in the README in the "style-configuration" section https://github.com/benoitsan/BBUncrustifyPlugin-Xcode#style-configuration
